services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://iris_adm:${DB_PASSWORD:-SENHA}@db:5432/iris_db
      - MODEL_SERVER_URL=http://ollama:11434
      - MODEL_NAME=llama3.2:3b
      - IRIS_NAME=Iris
    volumes:
      - .:/workspaces/iris
      - ./backend:/app
      - ./backend/static:/app/static
    depends_on:
      - db
      - ollama
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg17
    container_name: iris_db_container
    environment:
      - POSTGRES_USER=iris_adm
      - POSTGRES_PASSWORD=${DB_PASSWORD:-SENHA}
      - POSTGRES_DB=iris_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    command: ["serve"]
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:11434/api/health"]
      interval: 10s
      timeout: 3s
      retries: 6
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data: