version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=${DATABASE_URL:-postgresql://iris_adm@172.17.0.1:5432/iris_db}
    volumes:
      - .:/workspaces/iris
      - ./backend:/app
      - ./backend/static:/app/static
    restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - NODE_ENV=development
  #     - VITE_API_URL=http://localhost:8000
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend
  #   restart: unless-stopped