services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://iris_adm:${DB_PASSWORD}@db:5432/iris_db
    volumes:
      - .:/workspaces/iris
      - ./backend:/app
      - ./backend/static:/app/static
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg17
    container_name: iris_db_container
    environment:
      - POSTGRES_USER=iris_adm
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=iris_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data:
